### ISSUE TITLE
No class to run

### ISSUE THREAD

**Issue by NitKrishNit** [Workable/camel-rabbitmq-spring#1]
How to run this code.

**Comment by nikosd23** [comment]
You have to use this module as dependency in your project and add a route in the camel context.
Below you can see an example route with producer and consumer.

            <route id="testRoute">
                <from uri="rabbitmq-spring://get.failed.messages?cachingConnectionFactory=#cachingConnectionFactory&amp;maxConcurrentConsumers={{rabbitmq.messages.consumers}}&amp;concurrentConsumers={{rabbitmq.messages.consumers}}&amp;propertiesPrefix=rabbit"/>
                <to uri="bean:messageConverterProcessor?method=deserializeItem"/>
                <to uri="rabbitmq-spring://sync.response?producerTemplate=#rabbitTemplateSyncResponse"/>
            </route>
